include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
  exclude:
    - lib/src/generated/**

linter:
  rules:
    public_member_api_docs: false
