name: moinsen_cli
description: Say moinsen to help you with your flutter projects
version: 0.1.0
homepage: https://github.com/moinsen/moinsen_cli
repository: https://github.com/moinsen/moinsen_cli

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  fixnum: ^1.1.1
  grpc: ^4.0.1
  interact_cli: ^2.4.0
  mason_logger: ^0.3.2
  path: ^1.9.0
  protobuf: ^3.1.0
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  protoc_plugin: ^21.1.2
  test: ^1.25.14
  very_good_analysis: ^7.0.0

executables:
  moinsen: moinsen

builders:
  protoc_plugin:
    target: ":protoc_plugin"
    import: "package:protoc_plugin/protoc_plugin.dart"
    builder_factories: ["generateProto"]
    build_extensions: {".proto": [".pb.dart", ".pbenum.dart", ".pbgrpc.dart", ".pbjson.dart"]}
    auto_apply: dependents
    build_to: source
